export enum GroupCapability {
  RECYCLING_STATION_MANUFACTURER = 'RECYCLING_STATION_MANUFACTURER',
  RECYCLING_STATION_DISTRIBUTOR = 'RECYCLING_STATION_DISTRIBUTOR',
  RECYCLING_STATION_OWNER = 'RECYCLING_STATION_OWNER'
}